.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LFS\-MERGE\-DRIVER" "1" "May 2022" ""
.SH "NAME"
\fBgit\-lfs\-merge\-driver\fR \- Merge text\-based LFS files
.SH "SYNOPSIS"
\fBgit lfs merge\-driver\fR \fIoptions\fR
.SH "DESCRIPTION"
Merge text files stored in Git LFS using the default Git merge machinery, or a custom merge driver if specified\. Note that this, in general, does not support partial renames or copies because Git does not support them in this case\.
.P
This program is intended to be invoked automatically by Git and not by users manually\. See \fICONFIGURATION\fR for details on the configuration required for that\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fB\-\-ancestor\fR \fIpath\fR Specify the file containing the ancestor revision\.
.IP "\[ci]" 4
\fB\-\-current\fR \fIpath\fR Specify the file containing the current revision\.
.IP "\[ci]" 4
\fB\-\-marker\-size\fR \fInum\fR Specify the conflict marker size as an integer\.
.IP "\[ci]" 4
\fB\-\-other\fR \fIpath\fR Specify the file containing the other revision\.
.IP "\[ci]" 4
\fB\-\-program\fR \fIprogram\fR Specify a command, which is passed to the shell after substitution, that performs the actual merge\. If this is not specified, \fBgit merge\-file\fR is invoked with appropriate arguments to perform the merge of the file\.
.IP
See \fICONFIGURATION\fR for the sequences which are substituted here\.
.IP "" 0
.SH "CONFIGURATION"
Git allows the use of a custom merge driver for files based on the \fBmerge\fR attribute set in \fB\.gitattributes\fR\. By default, when using \fBgit lfs track\fR, this value is set to \fBlfs\fR\.
.P
Because Git LFS can be used to store both text and binary files and it isn\'t always clear which behavior should be used, Git LFS does not enable this merge driver by default\. However, if you know that some or all of your files are text files, then you can set the \fBmerge\fR attribute for those files to \fBlfs\-text\fR and use \fBgit config\fR to set the merge driver like so:
.P
\fBconsole $ git config merge\.lfs\-text\.driver \'git lfs merge\-driver \-\-ancestor %O \-\-current %A \-\-other %B \-\-marker\-size %L \-\-output %A\'\fR
.P
This tells Git to invoke the custom Git LFS merge driver, which in turn uses Git\'s merge machinery, to merge files where the \fBmerge\fR attribute is set to \fBlfs\-text\fR\. Note that \fBlfs\-text\fR here is an example and any syntactically valid value can be used\.
.P
If you are using a special type of file that needs rules different from Git\'s standard merge machinery, you can also specify the \fB\-\-program\fR option, which is passed to \fBsh\fR after substituting its own percent\-encoded escapes:
.IP "\[ci]" 4
\fB%A\fR: the current version
.IP "\[ci]" 4
\fB%B\fR: the other version
.IP "\[ci]" 4
\fB%D\fR: the destination version
.IP "\[ci]" 4
\fB%O\fR: the ancestor version
.IP "\[ci]" 4
\fB%L\fR: the conflict marker size
.IP "" 0
.P
Note that the percent sign must typically be doubled to prevent Git from substituting its own values here\. Therefore, specifying the default behavior explicitly looks like this:
.P
\fBconsole $ git config merge\.lfs\-text\.driver \e \'git lfs merge\-driver \-\-ancestor %O \-\-current %A \-\-other %B \-\-marker\-size %L \-\-output %A \-\-program \'\e\'\'git merge\-file \-\-stdout \-\-marker\-size=%%L %%A %%O %%B >%%D\'\e\'\'\'\fR
.P
The exit status from the custom command should be zero on success or non\-zero on conflicts or other failure\.
.P
Note that if no merge driver is specified for the value of the \fBmerge\fR attribute (as is the case by default with \fBmerge=lfs\fR), then the default Git merge strategy is used\. For LFS files, this means that Git will try to merge the pointer files, which usually is not useful\.
.SH "SEE ALSO"
git\-merge(1), git\-merge\-file(1), gitattributes(5)
.P
Part of the git\-lfs(1) suite\.
