.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LFS\-LOGS" "1" "May 2022" ""
.SH "NAME"
\fBgit\-lfs\-logs\fR \- Show errors from the git\-lfs command
.SH "SYNOPSIS"
\fBgit lfs logs\fR
.br
\fBgit lfs logs\fR \fIfile\fR
.br
\fBgit lfs logs clear\fR
.br
\fBgit lfs logs boomtown\fR
.br
.SH "DESCRIPTION"
Display errors from the git\-lfs command\. Any time it crashes, the details are saved to "\.git/lfs/logs"\.
.SH "COMMANDS"
.TP
\fBclear\fR
Clears all of the existing logged errors\.
.TP
\fBboomtown\fR
Triggers a dummy exception\.
.SH "OPTIONS"
Without any options, \fBgit lfs logs\fR simply shows the list of error logs\.
.TP
\fIfile\fR
Shows the specified error log\. Use "last" to show the most recent error\.
.SH "SEE ALSO"
Part of the git\-lfs(1) suite\.
