.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LFS\-UPDATE" "1" "May 2022" ""
.SH "NAME"
\fBgit\-lfs\-update\fR \- Update Git hooks
.SH "SYNOPSIS"
.TS
allbox;
\fBgit lfs update\fR [\-\-manual	\-\-force]
.TE
.SH "DESCRIPTION"
Updates the Git hooks used by Git LFS\. Silently upgrades known hook contents\. If you have your own custom hooks you may need to use one of the extended options below\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fB\-\-manual\fR \fB\-m\fR Print instructions for manually updating your hooks to include git\-lfs functionality\. Use this option if \fBgit lfs update\fR fails because of existing hooks and you want to retain their functionality\.
.IP "\[ci]" 4
\fB\-\-force\fR \fB\-f\fR Forcibly overwrite any existing hooks with git\-lfs hooks\. Use this option if \fBgit lfs update\fR fails because of existing hooks but you don\'t care about their current contents\.
.IP "" 0
.SH "SEE ALSO"
Part of the git\-lfs(1) suite\.
