.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LFS\-EXT" "1" "May 2022" ""
.SH "NAME"
\fBgit\-lfs\-ext\fR \- View extension details
.SH "SYNOPSIS"
\fBgit lfs ext list\fR [\fIname\fR\|\.\|\.\|\.]
.SH "DESCRIPTION"
Git LFS extensions enable the manipulation of files streams during smudge and clean\.
.SH "EXAMPLES"
.IP "\[ci]" 4
List details for all extensions
.IP
\fBgit lfs ext\fR \fBgit lfs ext list\fR
.IP "\[ci]" 4
List details for the specified extensions
.IP
\fBgit lfs ext list \'foo\' \'bar\'\fR
.IP "" 0
.SH "SEE ALSO"
Part of the git\-lfs(1) suite\.
