.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LFS\-ENV" "1" "May 2022" ""
.SH "NAME"
\fBgit\-lfs\-env\fR \- Display the Git LFS environment
.SH "SYNOPSIS"
\fBgit lfs env\fR
.SH "DESCRIPTION"
Display the current Git LFS environment\.
.SH "SEE ALSO"
Part of the git\-lfs(1) suite\.
